steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ltm-craftstudio-poc/cs-be-development-repo/cstudio-be:latest', '.']
    env:
      - 'DOCKER_BUILDKIT=1'
images:
  - 'us-central1-docker.pkg.dev/ltm-craftstudio-poc/cs-be-development-repo/cstudio-be:latest'
